project_id = "vhwjlztjrrlidjcmqhju"

[functions.chat]
verify_jwt = true

[functions.web-search]
verify_jwt = true

[functions.execute-code]
verify_jwt = true

[functions.generate-image]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true
